<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autodesk.Revit.SDK" Version="2020.2.1.2001" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Co.NamingLevelsPlugin.DI\Co.NamingLevelsPlugin.DI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if exist &quot;$(ProgramData)\Autodesk\Revit\Addins\2020\Co.NamingLevelsPlugin.RevitApp&quot; copy &quot;$(ProjectDir)$(OutputPath)*.dll&quot; &quot;$(ProgramData)\Autodesk\Revit\Addins\2020\Co.NamingLevelsPlugin.RevitApp&quot;" />
  </Target>

</Project>
